# NumPy
### [Documentation](https://numpy.org/doc/)
Installation using pip package installer and terminal:

`pip install numpy`

In [122]:
import numpy as np

### NumPy Array & Matrix

In [125]:
# NumPy array
a_list = [1,2,3,4]
x = np.array(a_list)
type(x)

numpy.ndarray

In [126]:
# NumPy matrix
a_matrix = [[1,2,3], [1,2,3], [1,2,3]]
y = np.array(a_matrix)
type(y)

numpy.ndarray

In [127]:
# NumPy range
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [128]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [129]:
# NumPy array of zeros
np.zeros(3)

array([0., 0., 0.])

In [130]:
# NumPy matrix of zeros
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [131]:
# NumPy array of ones
np.ones(3)

array([1., 1., 1.])

In [132]:
# Numpy matrix of ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [133]:
# NumPy array of linearly spaced points
np.linspace(0,20,41)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [134]:
# NumPy identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### NumPy Random

In [140]:
# NumPy random return a sample from uniform distribution
np.random.rand(3)

array([0.88049013, 0.66099876, 0.37178048])

In [136]:
np.random.rand(5,4)

array([[0.08098048, 0.30059703, 0.14863382, 0.41796482],
       [0.48522079, 0.99209395, 0.84666499, 0.41121028],
       [0.59676713, 0.31628562, 0.54982111, 0.37735485],
       [0.49378959, 0.6320386 , 0.55696999, 0.18828148],
       [0.84385423, 0.10283504, 0.12725358, 0.57000729]])

In [139]:
# NumPy random return a sample from standard distribution
np.random.randn(5)

array([-0.4523335 ,  0.20832818, -0.25016681, -0.6991287 ,  0.96025503])

In [141]:
np.random.randn(5,4)

array([[-0.03661145, -0.31925871,  0.19405194, -0.02265518],
       [-0.67459768,  1.37915108, -0.78819864, -0.08249221],
       [-0.28281323, -1.06628522,  0.67377289,  0.01764282],
       [ 1.17755016,  2.12961039,  0.36698291,  0.36488089],
       [-0.0741334 ,  1.90942849, -0.67115355, -0.65135199]])

In [142]:
np.random.randint(1,100,10)

array([40, 99, 48, 20, 12, 74, 93, 83, 55, 34])

In [143]:
arr  = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [144]:
arr.shape

(25,)

In [145]:
# Reshape an array into a matrix
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [146]:
arr.reshape(5,5).shape

(5, 5)

In [147]:
arr.dtype

dtype('int32')

In [148]:
ranarr.max()

46

In [149]:
# Index of the max value
ranarr.argmax()

4

### Numpy Operations

In [59]:
# Sum and deduction 
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [153]:
# Sum of rows of matrix
mat = np.arange(1,26).reshape(5,5)
np.sum(mat,1)

array([ 15,  40,  65,  90, 115])

In [152]:
# Sum of columns of matrix
np.sum(mat,0)

array([55, 60, 65, 70, 75])

In [61]:
# Multiplication
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [62]:
# devision
arr / arr

<ipython-input-62-ac92c0827e83>:2: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [63]:
1 / arr

<ipython-input-63-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [64]:
# Power
arr ** arr

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489], dtype=int32)

In [65]:
# Square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [66]:
# Exponential
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [68]:
# Maximum
np.max(arr)

9

In [69]:
# Sin
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [70]:
# Logarithm
np.log(arr)

<ipython-input-70-dcb25ea08282>:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [151]:
# Standard deviation
np.std(arr)

7.211102550927978

### NumPy Indexing & Broadcasting

In [77]:
arr = np.random.randint(0,100,10)

In [78]:
arr

array([15, 18, 27, 91, 32, 47, 99, 97, 79, 42])

In [102]:
# Array indexing
arr[8]

14

In [80]:
arr[1:5]

array([18, 27, 91, 32])

In [103]:
# Array broadcasting
arr_slice = arr[0:5]
arr_slice [:] = 100

In [98]:
arr

array([100, 100, 100, 100, 100,  86,  31,  49,  14,  37])

In [92]:
# Broadcasting changes the array itself, copy the array before broadcasting if the original is required
arr = np.random.randint(1,100,10)
arr_copy = arr.copy()
arr_copy

array([70, 97,  6, 46, 17, 86, 31, 49, 14, 37])

In [99]:
arr_slice = arr_copy[0:5]
arr_slice[:] = 200
arr_copy

array([200, 200, 200, 200, 200,  86,  31,  49,  14,  37])

In [106]:
# Matrix indexing
mat = np.array([[23,123,564],[756,952,165],[323,745,256]])
mat

array([[ 23, 123, 564],
       [756, 952, 165],
       [323, 745, 256]])

In [107]:
mat[0]

array([ 23, 123, 564])

In [109]:
mat[1][1]
mat[1,1]

952

In [114]:
mat[1:,1:]

array([[952, 165],
       [745, 256]])

In [116]:
# Conditional selection
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [120]:
bool_arr = arr > 5
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [121]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])